### ISSUE TITLE
diou loss problems

### ISSUE THREAD

**Issue by zhu2014yi** [Zzh-tju/DIoU-SSD-pytorch#17]
请问一下如果我要用真实的w和h，DIoU loss应该哪儿改一下，因为我看您这儿都是normalize之后的w和h？

**Comment by Zzh-tju** [comment]
你是说你的网络输出都是真实大小的变量吗？一种是你直接使用loss，但我不确定能正常训练。一种是你对所有变量统一除以图片的宽度，然后再使用loss

**Comment by zhu2014yi** [comment]
是的，都是真实变量，感谢解答。

Zzh-tju <notifications@github.com> 于2020年4月19日周日 上午1:58写道：

**Comment by zhu2014yi** [comment]
> 你是说你的网络输出都是真实大小的变量吗？一种是你直接使用loss，但我不确定能正常训练。一种是你对所有变量统一除以图片的宽度，然后再使用loss

另外我想问一下，直接训练我的REG loss是cls loss的10倍会不会影响训练效果（这个我还是在sum之后除了batch size的）。
Epoch: [1][80/3125] lr : 0.0100000 	 Batch Time: 0.202 	 Data Time:0.037 	CLS_Loss:0.38071	REG_Loss:4.19754 	 Loss:4.57824
Progress: 80 / 156250 [0%], Speed: 0.202 s/iter, ETA 0:08:45 (D:H:M)
PROGRESS: 0.05%
Epoch: [1][90/3125] lr : 0.0100000 	 Batch Time: 0.197 	 Data Time:0.038 	CLS_Loss:0.36623	REG_Loss:4.08735 	 Loss:4.45357
Progress: 90 / 156250 [0%], Speed: 0.197 s/iter, ETA 0:08:33 (D:H:M)

**Comment by Zzh-tju** [comment]
对于特定的数据集，损失权重都会不同，也与类别数量有关

**Comment by zhu2014yi** [comment]
> 对于特定的数据集，损失权重都会不同，也与类别数量有关

好的，非常感谢。
